_BASE_: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  ROI_HEADS:
    NUM_CLASSES: 8
    SCORE_THRESH_TEST: 0.5
INPUT:
  MIN_SIZE_TRAIN: (640, 800, 960)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.00025
  MAX_ITER: 1500
  STEPS: (1000, 1300)
  CHECKPOINT_PERIOD: 500
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  TRAIN: ("newspaper_train",)
  TEST: ("newspaper_val",)
